version: "3"
services:
  villetta-app:
    image: francesco99975/villetta-app
    stdin_open: true
    ports:
      - "80:80"
    networks:
      - villetta-net
    depends_on:
      - "payment-server"
      - "admin-server"
  payment-server:
    image: francesco99975/villetta-payment-server
    ports:
      - "3000:3000"
    networks:
      - villetta-net
    volumes:
      - villetta-invoice-data
    depends_on:
      - "mongo"
  admin-server:
    image: francesco99975/villetta-admin-server
    ports:
      - "8080:8000"
    networks:
      - villetta-net
    volumes:
      - villetta-img-data
    depends_on:
      - postgres
  mongo:
    image: "mongo"
    ports:
      - "2717:27017"
    networks:
      - villetta-net
    volumes:
      - villetta-orders-data:/data/db
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_USER=francesco"
      - "POSTGRES_PASSWORD=gogetassgss3"
      - "POSTGRES_DB=villettadb"
    ports:
      - "5433:5433"
    networks:
      - villetta-net
    volumes:
      - villetta-admin-data:/data/db

networks:
  villetta-net:
    driver: bridge

volumes:
  villetta-invoice-data:
    driver: local
  villetta-img-data:
    driver: local
  villetta-orders-data:
    driver: local
  villetta-admin-data:
    driver: local
